import {systems,predict,z} from '../../spirolab-core/src/reference.js';
import {solveCurve} from '../../spirolab-core/src/solver.js';
import {interpret} from '../../spirolab-core/src/interpretation.js';
const $=(s)=>document.querySelector(s), clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const state={age:45,height:172,sex:'M',population:'adult',system:'gli2022',group:'Global',fvc:4.35,fev1:3.35,pef:9.1,fef25:7.0,fef50:4.6,fef75:1.7,pif:6.2,mode:'linked',tab:'analysis',quality:{cough:false,leak:false,early:false,bev:.08,repro:.10,maneuvers:3}};
const presets={normal:{fvc:4.35,fev1:3.35,pef:9.1,fef25:7,fef50:4.6,fef75:1.7},mild:{fvc:4.1,fev1:2.55,pef:7.2,fef25:4.5,fef50:2.3,fef75:.7},severe:{fvc:3.45,fev1:1.25,pef:4.4,fef25:2.6,fef50:1.1,fef75:.3},restrictive:{fvc:2.55,fev1:2.15,pef:7.4,fef25:6.0,fef50:4.0,fef75:1.5},mixed:{fvc:2.5,fev1:1.3,pef:4.8,fef25:2.7,fef50:1.25,fef75:.35},prism:{fvc:3.4,fev1:2.35,pef:7.0,fef25:5.3,fef50:3.3,fef75:1.1}};
function field(id,label,min,max,step,unit){return `<div class="field"><label>${label}<b id="${id}Out">${state[id].toFixed(step<1?2:0)} ${unit}</b></label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${state[id]}"></div>`}
function render(){
 const groupOptions=systems[state.system].groups.map(g=>`<option ${g===state.group?'selected':''}>${g}</option>`).join('');
 $('#app').innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><div class="logo">SL</div><div><h1>SpiroLab AI-UCH</h1><small>Motor fisiológico de simulación espirométrica</small></div></div><div class="top-actions"><button class="btn" id="share">Compartir</button><button class="btn" id="print">Informe</button><button class="btn primary" id="fullscreen">Pantalla completa</button></div></header><div class="workspace">
 <aside class="panel sidebar"><div class="section-title">Paciente virtual</div><div class="two"><div class="field"><label>Edad</label><input id="age" type="number" value="${state.age}"></div><div class="field"><label>Talla (cm)</label><input id="height" type="number" value="${state.height}"></div></div><div class="two"><div class="field"><label>Sexo</label><select id="sex"><option value="M" ${state.sex==='M'?'selected':''}>Masculino</option><option value="F" ${state.sex==='F'?'selected':''}>Femenino</option></select></div><div class="field"><label>Población</label><select id="population"><option value="adult">Adulto</option><option value="pediatric">Pediátrico</option></select></div></div><div class="field"><label>Ecuación de referencia</label><select id="system">${Object.entries(systems).map(([k,v])=>`<option value="${k}" ${k===state.system?'selected':''}>${v.label}</option>`).join('')}</select></div><div class="field"><label>Grupo de referencia</label><select id="group">${groupOptions}</select></div>
 <div class="section-title">Patrones rápidos</div><div class="preset-grid">${Object.entries({normal:'Normal',mild:'Obstructivo leve',severe:'Obstructivo severo',restrictive:'Restrictivo probable',mixed:'Mixto probable',prism:'PRISm'}).map(([k,v])=>`<button class="preset" data-preset="${k}">${v}</button>`).join('')}</div>
 <div class="section-title">Variables primarias</div>${field('fvc','CVF',.5,8,.01,'L')}${field('fev1','VEF₁',.3,7,.01,'L')}${field('pef','PEF',1,14,.05,'L/s')}${field('pif','PIF',1,12,.05,'L/s')}
 <div class="section-title">Motor de curva</div><div class="switchline"><span style="font-size:12px">Edición avanzada de FEF</span><button class="switch ${state.mode==='advanced'?'on':''}" id="mode"></button></div><div id="fefControls">${field('fef25','FEF₂₅',.2,12,.05,'L/s')}${field('fef50','FEF₅₀',.1,10,.05,'L/s')}${field('fef75','FEF₇₅',.05,6,.05,'L/s')}</div></aside>
 <main class="main"><section class="panel hero"><div><h2>Simulador fisiológico</h2><p>CVF, VEF₁ y PEF como restricciones duras; flujos instantáneos como restricciones blandas.</p></div><div class="status" id="solverStatus">Solver convergente</div></section><section class="charts"><div class="panel chart-card"><div class="chart-head"><strong>Curva flujo–volumen</strong><span>Flujo (L/s) · Volumen (L)</span></div><svg id="fv"></svg></div><div class="panel chart-card"><div class="chart-head"><strong>Curva volumen–tiempo</strong><span>Volumen (L) · Tiempo (s)</span></div><svg id="vt"></svg></div></section><section class="metrics" id="metrics"></section><section class="panel"><div class="tabs">${['analysis','quality','broncho','teacher','developer'].map(t=>`<button class="tab ${state.tab===t?'active':''}" data-tab="${t}">${({analysis:'Análisis',quality:'Calidad',broncho:'Broncodilatador',teacher:'Modo docente',developer:'Desarrollador'})[t]}</button>`).join('')}</div><div class="content-panel" id="tabContent"></div></section></main>
 <aside class="rightbar"><section class="panel interpretation" id="interpretation"></section><section class="panel solver" id="solverPanel"></section><section class="panel interpretation"><div class="section-title">Valores de referencia</div><table class="table" id="refTable"></table></section></aside></div><footer class="footer">Uso educativo y de investigación. No sustituye software clínico validado ni la interpretación profesional.</footer></div>`;
 bind();update();
}
function bind(){
 ['age','height','sex','population','system','group'].forEach(id=>$('#'+id)?.addEventListener('change',e=>{state[id]=['age','height'].includes(id)?+e.target.value:e.target.value;if(id==='system'){state.group=systems[state.system].groups[0];render()}else update()}));
 ['fvc','fev1','pef','pif','fef25','fef50','fef75'].forEach(id=>$('#'+id)?.addEventListener('input',e=>{state[id]=+e.target.value;update()}));
 document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{Object.assign(state,presets[b.dataset.preset]);render()});
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));updateTab()});
 $('#mode').onclick=()=>{state.mode=state.mode==='linked'?'advanced':'linked';render()};
 $('#fullscreen').onclick=()=>document.documentElement.requestFullscreen?.(); $('#print').onclick=()=>print(); $('#share').onclick=async()=>{try{await navigator.share({title:'SpiroLab AI-UCH',url:location.href})}catch{await navigator.clipboard.writeText(location.href);alert('Enlace copiado')}};
}
function linkedTargets(){if(state.mode!=='linked')return;const r=clamp(state.fev1/state.fvc,.22,.9),severity=clamp((.82-r)/.5,0,1);state.fef25=state.pef*(.72-.16*severity);state.fef50=state.pef*(.50-.28*severity);state.fef75=state.pef*(.20-.14*severity)}
function update(){linkedTargets();['fvc','fev1','pef','pif','fef25','fef50','fef75'].forEach(id=>{const o=$('#'+id+'Out');if(o)o.textContent=`${state[id].toFixed(2)} ${id.includes('fef')||id==='pef'||id==='pif'?'L/s':'L'}`;const el=$('#'+id);if(el&&state.mode==='linked'&&id.startsWith('fef')){el.value=state[id];el.disabled=true}});
 const pred=predict(state);const input={...state};const sol=solveCurve(input);const m={fvc:state.fvc,fev1:state.fev1,ratio:state.fev1/state.fvc,pef:state.pef};const it=interpret(m,pred);drawFV(sol);drawVT(sol);renderMetrics(m,pred,sol);renderInterpretation(it,m,pred);renderSolver(sol);renderRefs(m,pred);updateTab(sol,pred,m);
}
function axes(svg,xMax,yMin,yMax,xLabel,yLabel){const W=700,H=315,p={l:48,r:18,t:18,b:34};svg.setAttribute('viewBox',`0 0 ${W} ${H}`);let h='';for(let i=0;i<=5;i++){const x=p.l+(W-p.l-p.r)*i/5;h+=`<line class="grid-line" x1="${x}" y1="${p.t}" x2="${x}" y2="${H-p.b}"/><text class="axis-label" x="${x}" y="${H-13}" text-anchor="middle">${(xMax*i/5).toFixed(1)}</text>`}for(let i=0;i<=6;i++){const y=p.t+(H-p.t-p.b)*i/6,val=yMax-(yMax-yMin)*i/6;h+=`<line class="grid-line" x1="${p.l}" y1="${y}" x2="${W-p.r}" y2="${y}"/><text class="axis-label" x="${p.l-8}" y="${y+3}" text-anchor="end">${val.toFixed(1)}</text>`}h+=`<line class="axis" x1="${p.l}" y1="${H-p.b}" x2="${W-p.r}" y2="${H-p.b}"/><line class="axis" x1="${p.l}" y1="${p.t}" x2="${p.l}" y2="${H-p.b}"/>`;return {W,H,p,h,X:v=>p.l+v/xMax*(W-p.l-p.r),Y:v=>p.t+(yMax-v)/(yMax-yMin)*(H-p.t-p.b)}}
function path(points,X,Y){return points.map((d,i)=>`${i?'L':'M'}${X(d.x).toFixed(2)},${Y(d.y).toFixed(2)}`).join(' ')}
function drawFV(sol){const svg=$('#fv'),ymax=Math.max(12,state.pef*1.2),a=axes(svg,state.fvc*1.12,-Math.max(8,state.pif*1.25),ymax);const exp=sol.exp.map(d=>({x:d.v,y:d.q})),insp=sol.insp.map(d=>({x:d.v,y:d.q}));svg.innerHTML=a.h+`<path class="curve" d="${path(exp,a.X,a.Y)}"/><path class="curve-secondary" d="${path(insp,a.X,a.Y)}"/>`+[[.25,state.fef25],[.5,state.fef50],[.75,state.fef75]].map(([x,y])=>`<circle class="point" cx="${a.X(state.fvc*x)}" cy="${a.Y(y)}" r="4"/>`).join('')}
function drawVT(sol){const svg=$('#vt'),tmax=Math.min(16,Math.max(6,sol.fet*1.08)),a=axes(svg,tmax,0,state.fvc*1.15);const pts=sol.timeline.filter((_,i)=>i%4===0).map(d=>({x:Math.min(d.t,tmax),y:d.v}));svg.innerHTML=a.h+`<path class="curve" d="${path(pts,a.X,a.Y)}"/><line x1="${a.X(1)}" y1="${a.Y(0)}" x2="${a.X(1)}" y2="${a.Y(state.fev1)}" stroke="#ffcc66" stroke-dasharray="5 5"/><circle class="point" cx="${a.X(1)}" cy="${a.Y(sol.generatedFEV1)}" r="4"/>`}
function renderMetrics(m,p,s){const data=[['CVF',m.fvc,'L',z(m.fvc,p.fvc,p.sd.fvc)],['VEF₁',m.fev1,'L',z(m.fev1,p.fev1,p.sd.fev1)],['VEF₁/CVF',m.ratio*100,'%',z(m.ratio,p.ratio,p.sd.ratio)],['PEF',m.pef,'L/s',z(m.pef,p.pef,p.sd.pef)],['FEF₂₅–₇₅',(s.generatedFEFs.fef25+s.generatedFEFs.fef50+s.generatedFEFs.fef75)/3,'L/s',null],['FET',s.fet,'s',null]];$('#metrics').innerHTML=data.map(([n,v,u,zz])=>`<div class="panel metric"><div class="name">${n}</div><div class="value">${v.toFixed(n==='VEF₁/CVF'?1:2)} <small>${u}</small></div><div class="sub">${zz==null?'Generado por el modelo':`z-score ${zz.toFixed(2)}`}</div></div>`).join('')}
function renderInterpretation(it,m,p){$('#interpretation').innerHTML=`<span class="result-badge">Interpretación automática</span><h3>${it.title}</h3><p>${it.detail}</p><div class="notice">Cociente medido: ${(m.ratio*100).toFixed(1)}% · LLN: ${(p.lln.ratio*100).toFixed(1)}%. CVF: ${m.fvc.toFixed(2)} L · LLN: ${p.lln.fvc.toFixed(2)} L.</div>`}
function renderSolver(s){$('#solverPanel').innerHTML=`<div class="section-title">Estado del solver</div><div class="solver-row"><span>Coherencia interna</span><b>${s.coherence.toFixed(1)}%</b></div><div class="bar"><i style="width:${s.coherence}%"></i></div><div class="solver-row"><span>VEF₁ objetivo</span><b>${state.fev1.toFixed(3)} L</b></div><div class="solver-row"><span>VEF₁ generado</span><b>${s.generatedFEV1.toFixed(3)} L</b></div><div class="solver-row"><span>Error absoluto</span><b>${Math.abs(s.generatedFEV1-state.fev1).toFixed(3)} L</b></div><div class="solver-row"><span>Iteraciones</span><b>${s.iterations}</b></div>`;$('#solverStatus').textContent=s.coherence>95?'Solver convergente':'Revisar coherencia de entradas'}
function renderRefs(m,p){$('#refTable').innerHTML=`<tr><th>Variable</th><th>Medido</th><th>Pred.</th><th>LLN</th><th>%Pred.</th></tr>${[['CVF',m.fvc,p.fvc,p.lln.fvc],['VEF₁',m.fev1,p.fev1,p.lln.fev1],['VEF₁/CVF',m.ratio,p.ratio,p.lln.ratio],['PEF',m.pef,p.pef,p.lln.pef]].map(([n,a,b,c])=>`<tr><td>${n}</td><td>${n==='VEF₁/CVF'?(a*100).toFixed(1)+'%':a.toFixed(2)}</td><td>${n==='VEF₁/CVF'?(b*100).toFixed(1)+'%':b.toFixed(2)}</td><td>${n==='VEF₁/CVF'?(c*100).toFixed(1)+'%':c.toFixed(2)}</td><td>${(a/b*100).toFixed(0)}%</td></tr>`).join('')}`}
function updateTab(sol,p,m){const el=$('#tabContent');if(!el)return;if(state.tab==='analysis')el.innerHTML=`<div class="advanced-grid"><div class="case-card"><strong>Restricciones duras</strong><span>CVF ${state.fvc.toFixed(2)} L · VEF₁ ${state.fev1.toFixed(2)} L · PEF ${state.pef.toFixed(2)} L/s</span></div><div class="case-card"><strong>Restricciones blandas</strong><span>FEF₂₅ ${state.fef25.toFixed(2)} · FEF₅₀ ${state.fef50.toFixed(2)} · FEF₇₅ ${state.fef75.toFixed(2)} L/s</span></div></div><p class="notice">La concavidad emerge de la solución conjunta. En modo vinculado, los FEF se recalculan al modificar VEF₁, CVF o PEF. En edición avanzada se conservan como objetivos blandos y el software muestra la coherencia alcanzada.</p>`;
 else if(state.tab==='quality')el.innerHTML=`<div class="advanced-grid">${['Inicio satisfactorio','Sin tos en primer segundo','Sin fuga','Final espiratorio adecuado','Repetibilidad ≤150 mL','≥3 maniobras aceptables'].map((x,i)=>`<div class="case-card"><strong>${i<4?'✓':'●'} ${x}</strong><span>${i<4?'Criterio simulado como aceptable':'Configurable en una próxima iteración del módulo'}</span></div>`).join('')}</div>`;
 else if(state.tab==='broncho')el.innerHTML=`<div class="case-card"><strong>Simulación broncodilatadora</strong><span>Seleccione un cambio de VEF₁ y CVF para comparar curvas pre/post. El módulo usará los mismos controles de coherencia del solver.</span></div>`;
 else if(state.tab==='teacher')el.innerHTML=`<div class="advanced-grid"><div class="case-card"><strong>Crear caso oculto</strong><span>Guarda la configuración actual sin mostrar interpretación.</span></div><div class="case-card"><strong>Revelar respuesta</strong><span>Presenta patrón, variables críticas y razonamiento interpretativo.</span></div></div>`;
 else el.innerHTML=`<table class="table"><tr><th>Parámetro interno</th><th>Valor</th></tr><tr><td>a (decaimiento)</td><td>${sol.params[0].toFixed(4)}</td></tr><tr><td>b (forma media)</td><td>${sol.params[1].toFixed(4)}</td></tr><tr><td>c (forma terminal)</td><td>${sol.params[2].toFixed(4)}</td></tr><tr><td>Función objetivo</td><td>${sol.loss.toFixed(6)}</td></tr><tr><td>FET modelado</td><td>${sol.fet.toFixed(3)} s</td></tr></table>`}
render();
