import { REFERENCE_CATALOG } from '../core/reference-engine.js';
import { DISEASES } from '../core/pathology-engine.js';

const options = (catalog) => Object.entries(catalog).map(([value, item]) => `<option value="${value}">${item.label}</option>`).join('');
export function appTemplate() {
  return `<header class="topbar"><div class="brand"><div class="logo">SL</div><div><b>SpiroLab AI-UCH</b><small>Motor educativo de espirometría · v1.0 α</small></div></div><nav><button class="nav active">Simulador</button><button class="nav">Calidad</button><button class="nav">Docencia</button></nav><div class="actions"><button id="shareBtn">Compartir</button><button onclick="window.print()">Informe</button></div></header>
  <main class="dashboard"><aside class="panel controls"><h2>Generador</h2>
  <section><h4>Paciente virtual</h4><label>Sexo<select id="sex"><option value="M">Masculino</option><option value="F">Femenino</option></select></label><label>Edad<input id="age" type="number" min="3" max="95" value="45"></label><label>Estatura (cm)<input id="height" type="number" min="90" max="210" value="172"></label></section>
  <section><h4>Referencia</h4><label>Ecuación<select id="reference">${options(REFERENCE_CATALOG)}</select></label><label>Grupo<select id="group"><option>Global</option></select></label></section>
  <section><h4>Paciente fisiopatológico</h4><label>Condición<select id="disease">${options(DISEASES)}</select></label><label>Severidad<select id="severity"><option value="0">Sin alteración</option><option value="1">Leve</option><option value="2">Moderada</option><option value="3">Grave</option><option value="4">Muy grave</option></select></label><button class="primary" id="applyProfile">Aplicar perfil fisiopatológico</button><p id="diseaseNote" class="note"></p></section>
  <section><h4>Variables</h4>${slider('fvc','CVF','2','8','0.01')}${slider('fev1','VEF₁','0.3','7','0.01')}${slider('pef','PEF','1','15','0.1')}${slider('fivc','CVIF','2','8','0.01')}</section>
  <section><h4>Índices fisiológicos docentes</h4>${coloredSlider('resistance','Resistencia de vía aérea')}${coloredSlider('smallAirways','Compromiso de vía aérea pequeña')}${coloredSlider('elasticRecoil','Retroceso elástico')}</section>
  <section><label class="check"><input type="checkbox" id="showPredicted" checked> Mostrar curva predicha</label><label class="check"><input type="checkbox" id="showPoints"> Mostrar puntos de control</label></section></aside>
  <section class="center"><article class="panel chart"><div class="chart-head"><h2>Curva flujo–volumen</h2><span id="morphologyBadge"></span></div><svg id="flowChart"></svg></article><article class="panel chart"><div class="chart-head"><h2>Curva volumen–tiempo</h2><span>VEF₁ calculado desde la curva</span></div><svg id="timeChart"></svg></article></section>
  <aside class="panel results"><h2>Resultados e interpretación</h2><div class="metric-grid" id="metrics"></div><div id="interpretation"></div><div class="table-wrap"><table><thead><tr><th>Variable</th><th>Medido</th><th>Predicho</th><th>%Pred</th><th>z</th></tr></thead><tbody id="resultsBody"></tbody></table></div><div id="qualityBox" class="quality"></div><div class="warning">Motor educativo. Las ecuaciones predictivas son aproximaciones demostrativas y no deben utilizarse para decisiones clínicas.</div></aside></main>`;
}
function slider(id,label,min,max,step){return `<label class="slider-label"><span>${label}</span><input id="${id}" type="range" min="${min}" max="${max}" step="${step}"><output id="${id}Out"></output></label>`;}
function coloredSlider(id,label){return `<label class="slider-label phys"><span>${label}</span><input class="colored" id="${id}" type="range" min="0" max="100" step="1"><output id="${id}Out"></output></label>`;}
